name: Build and Test
on: ["push", "pull_request"]
  
jobs:
    # test:
    #     name: Test
    #     runs-on: ubuntu-latest
    #     steps:
    #         - uses: actions/checkout@v2

    #         - name: Setup go
    #           uses: actions/setup-go@v2
    #           with:
    #             go-version: 1.14

    #         - name: install dependencies
    #           run: |
    #             sudo apt-get update
    #             sudo apt-get install -qq libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev

    #         - name: Run Unit tests.
    #           run: make test

    #         - name: Convert coverage to lcov
    #           uses: jandelgado/gcov2lcov-action@v1.0.0
    #           with:
    #               infile: coverage.out
    #               outfile: coverage.lcov

    #         - name: Coveralls
    #           uses: coverallsapp/github-action@master
    #           with:
    #             github-token: ${{ secrets.GITHUB_TOKEN }}
    #             path-to-lcov: ./coverage.lcov

    build:
        name: Build
        runs-on: ubuntu-latest 
        steps:
            - uses: actions/checkout@v2

            - name: Setup go
              uses: actions/setup-go@v2
              with:
                go-version: 1.14

            - name: install dependencies
              run: |
                sudo apt-get update
                sudo apt-get install -qq libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev

            - name: Build
              run: make
